### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by B-3PO** [webformula/pax-components#13]
##### TODO
- [x] create basic component
- [x] add hoisting to body
- [x] rework css so the component works without wc
