### ISSUE TITLE
Select

### ISSUE THREAD

**Issue by B-3PO** [webformula/pax-components#24]
##### TODO
- [x] create basic component
- [x] add enhanced dropdown
- [x] rework css so the component works without wc
- [x] fix initially selected option
- [x] hoist panel to body
- [x] fix focused bottom border (its shifting the text)
- [x] add shaped version
- [x] add key commands
- [x] make sure the panel is removed when the component is removed
