### ISSUE TITLE
cards

### ISSUE THREAD

**Issue by B-3PO** [webformula/pax-components#25]
##### TODO
- [x] create basic component
- [ ] add ripple to content-action
- [ ] add text over media support
- [ ] add horizontal media support
