### ISSUE TITLE
Banner

### ISSUE THREAD

**Issue by B-3PO** [webformula/pax-components#26]
##### TODO
- [x] create base component
- [ ] test without top app bar
- [ ] test with multiple top app bar states
