### ISSUE TITLE
Navigation drawer

### ISSUE THREAD

**Issue by B-3PO** [webformula/pax-components#27]
##### TODO
- [x] create base component
- [x] add dismissible mode
- [x] add modal mode
- [x] add open / close animation
