### ISSUE TITLE
Top app bar

### ISSUE THREAD

**Issue by B-3PO** [webformula/pax-components#28]
##### TODO
- [x] create standard state
- [x] create fixed state
- [x] rework css so the component works without wc
- [ ] create dense state
- [ ] create prominent state
- [ ] create short state
- [ ] create always collapsed short state
- [ ] add more classes to spacer based on prominent, dense. [file](https://github.com/webformula/pax-components/blob/master/src/components/top-app-bar/index.js#L21)
