### ISSUE TITLE
Checkboxes

### ISSUE THREAD

**Issue by B-3PO** [webformula/pax-components#3]
##### TODO
- [x] create page
- [x] update docs when component is updated
- [x] add theming section

- [x] optimize templating (look at switch)
