### ISSUE TITLE
Panel

### ISSUE THREAD

**Issue by B-3PO** [webformula/pax-components#6]
##### TODO
- [x] create page
- [x] update positioning to use css
- [x] fix open and close animations
- [x] add position selection interface
- [x] update page with component
- [x] figure out why re-rendering selects(container, position) disconnects there on-change events
